data:
  csv_file_path: samples_data.csv
  csv_output_path: samples_data.csv
  data_path: data/matfiles
  file_names:
  - normal_0.mat
  - IR007_0.mat
  - B007_0.mat
  - OR007@6_0.mat
  - IR014_0.mat
  - B014_0.mat
  - OR014@6_0.mat
  - IR021_0.mat
  - B021_0.mat
  - OR021@6_0.mat
  image_size: 224
  img_output_dir: data/STFTimages
  overlap_ratio: 0.5
  sampling_frequency: 12000
  split_ratios:
  - 0.7
  - 0.2
  - 0.1
  stft_overlap: 0.5
  stft_window_size: 64
  time_steps: 1024
  truncated_value: 102912
model:
  name: ResNet18_CWRU
  num_classes: 10
train:
  batch_size: 32
  checkpoint_dir: checkpoints/run1
  learning_rate: 0.001
  num_epochs: 20
